language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "10"
  - "12"
  - "14"

before_script:
  - ssh-keygen -t rsa -C "you@example.com"


script:
  - npm run eslint
  - npm run test-cov

after_script:
  - npm install coveralls
  - nyc report --reporter=text-lcov | coveralls